name: Deploy static HTML site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload HTML to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: .  # Change if your HTML is in /public or /build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2